import { AppState, Child, Parent, Staff, Appointment, Attendance, Payment, Session } from '@/types';

// Today's date helper (ISO format YYYY-MM-DD)
const today = new Date().toISOString().split('T')[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];

export const initialParents: Parent[] = [
  {
    id: 'parent-1',
    nameAr: 'محمد مصطفى الشناوي',
    nameEn: 'Mohamed Mostafa El-Shenawy',
    relationship: 'FATHER',
    phone: '01012345678',
    secondaryPhone: '01298765432',
    email: 'mohamed.shenawy@example.com',
    nationalId: '28910120101234',
    address: 'مدينة نصر، القاهرة',
    notes: 'يفضل التواصل في الفترة المسائية',
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'parent-2',
    nameAr: 'منى إبراهيم خليل',
    nameEn: 'Mona Ibrahim Khalil',
    relationship: 'MOTHER',
    phone: '01123456789',
    secondaryPhone: '',
    email: 'mona.ibrahim@example.com',
    nationalId: '29205150105678',
    address: 'المعادي، القاهرة',
    notes: 'الأم تتابع كافة الجلسات بانتظام',
    createdAt: '2026-01-15T11:30:00Z',
  },
  {
    id: 'parent-3',
    nameAr: 'حسن عبد الله النجار',
    nameEn: 'Hassan Abdullah El-Naggar',
    relationship: 'FATHER',
    phone: '01234567890',
    secondaryPhone: '01099887766',
    email: 'hassan.naggar@example.com',
    nationalId: '28503200109876',
    address: 'الدقي، الجيزة',
    notes: '',
    createdAt: '2026-02-01T09:15:00Z',
  },
  {
    id: 'parent-4',
    nameAr: 'رانيا طارق منصور',
    nameEn: 'Rania Tarek Mansour',
    relationship: 'MOTHER',
    phone: '01512349876',
    secondaryPhone: '',
    email: 'rania.tarek@example.com',
    nationalId: '29411080103456',
    address: 'التجمع الخامس، القاهرة الجديدة',
    notes: '',
    createdAt: '2026-02-12T14:00:00Z',
  },
];

export const initialStaff: Staff[] = [
  {
    id: 'staff-1',
    nameAr: 'د. خالد منصور القاضي',
    nameEn: 'Dr. Khaled Mansour El-Kady',
    role: 'ADMIN',
    specialty: 'SPEECH_THERAPY',
    phone: '01001112223',
    email: 'dr.khaled@speechcenter-demo.eg',
    active: true,
    color: '#0d9488', // teal
    joinedDate: '2025-01-01',
  },
  {
    id: 'staff-2',
    nameAr: 'أ. سارة أحمد رضوان',
    nameEn: 'Ms. Sara Ahmed Radwan',
    role: 'THERAPIST',
    specialty: 'SPEECH_THERAPY',
    phone: '01112223334',
    email: 'sara.ahmed@speechcenter-demo.eg',
    active: true,
    color: '#3b82f6', // blue
    joinedDate: '2025-02-01',
  },
  {
    id: 'staff-3',
    nameAr: 'أ. محمد علي عثمان',
    nameEn: 'Mr. Mohamed Ali Othman',
    role: 'SPECIALIST',
    specialty: 'SKILLS_DEVELOPMENT',
    phone: '01223334445',
    email: 'mohamed.ali@speechcenter-demo.eg',
    active: true,
    color: '#8b5cf6', // purple
    joinedDate: '2025-02-15',
  },
  {
    id: 'staff-4',
    nameAr: 'أ. نور حسن عبد الرحمن',
    nameEn: 'Ms. Nour Hassan Abdel-Rahman',
    role: 'SPECIALIST',
    specialty: 'BEHAVIOR_MODIFICATION',
    phone: '01098887776',
    email: 'nour.hassan@speechcenter-demo.eg',
    active: true,
    color: '#f59e0b', // amber
    joinedDate: '2025-03-01',
  },
  {
    id: 'staff-5',
    nameAr: 'أ. هدى كمال فهمي',
    nameEn: 'Ms. Hoda Kamal Fahmy',
    role: 'RECEPTIONIST',
    specialty: 'ADMINISTRATION',
    phone: '01556667778',
    email: 'hoda.kamal@speechcenter-demo.eg',
    active: true,
    color: '#ec4899', // pink
    joinedDate: '2025-03-10',
  },
];

export const initialChildren: Child[] = [
  {
    id: 'child-1',
    nameAr: 'أحمد محمد الشناوي',
    nameEn: 'Ahmed Mohamed El-Shenawy',
    birthDate: '2020-04-12',
    gender: 'MALE',
    parentId: 'parent-1',
    assignedStaffIds: ['staff-2', 'staff-3'],
    diagnosisSummary: 'تأخر لغوي نمائي ولدغة في حرف الراء (ر)',
    status: 'ACTIVE',
    emergencyContact: '01012345678',
    createdAt: '2026-01-10T10:30:00Z',
  },
  {
    id: 'child-2',
    nameAr: 'يوسف علي إبراهيم',
    nameEn: 'Youssef Ali Ibrahim',
    birthDate: '2019-09-20',
    gender: 'MALE',
    parentId: 'parent-2',
    assignedStaffIds: ['staff-2', 'staff-4'],
    diagnosisSummary: 'تشتت انتباه وفرط حركة مع صعوبات نطق',
    status: 'ACTIVE',
    emergencyContact: '01123456789',
    createdAt: '2026-01-15T12:00:00Z',
  },
  {
    id: 'child-3',
    nameAr: 'مريم حسن النجار',
    nameEn: 'Mariam Hassan El-Naggar',
    birthDate: '2021-02-05',
    gender: 'FEMALE',
    parentId: 'parent-3',
    assignedStaffIds: ['staff-2'],
    diagnosisSummary: 'تأتأة (حبسة كلامية) خفيفة عند بدء الكلام',
    status: 'ACTIVE',
    emergencyContact: '01234567890',
    createdAt: '2026-02-01T09:45:00Z',
  },
  {
    id: 'child-4',
    nameAr: 'سارة محمود طارق',
    nameEn: 'Sara Mahmoud Tarek',
    birthDate: '2018-11-30',
    gender: 'FEMALE',
    parentId: 'parent-4',
    assignedStaffIds: ['staff-3', 'staff-4'],
    diagnosisSummary: 'صعوبات تعلم وتأهيل مهارات ما قبل القراءة',
    status: 'ASSESSMENT',
    emergencyContact: '01512349876',
    createdAt: '2026-02-12T14:30:00Z',
  },
  {
    id: 'child-5',
    nameAr: 'عمر هاني عادل',
    nameEn: 'Omar Hany Adel',
    birthDate: '2020-07-18',
    gender: 'MALE',
    parentId: 'parent-1',
    assignedStaffIds: ['staff-2'],
    diagnosisSummary: 'خنف وخلل في مخرج حرفي (ك - ج)',
    status: 'ACTIVE',
    emergencyContact: '01012345678',
    createdAt: '2026-02-20T11:00:00Z',
  },
];

export const initialAppointments: Appointment[] = [
  // Appointment 1: Today, 1:1, with Sara Ahmed
  {
    id: 'apt-1',
    childIds: ['child-1'],
    staffIds: ['staff-2'],
    date: today,
    startTime: '10:00',
    endTime: '10:45',
    status: 'SCHEDULED',
    sessionStatus: 'SCHEDULED',
    attendanceStatus: 'PRESENT',
    paymentStatus: 'PAID',
    amount: 350,
    sessionType: 'INDIVIDUAL',
    room: 'عيادة التخاطب 1',
    notes: 'تدريب على مخرج حرف الراء والتهيئة الصوتية',
    hasConflict: false,
    createdAt: '2026-02-15T08:00:00Z',
  },
  // Appointment 2: Today, 1:1, with Mohamed Ali
  {
    id: 'apt-2',
    childIds: ['child-2'],
    staffIds: ['staff-3'],
    date: today,
    startTime: '11:00',
    endTime: '11:45',
    status: 'SCHEDULED',
    sessionStatus: 'SCHEDULED',
    attendanceStatus: 'PENDING',
    paymentStatus: 'PARTIAL',
    amount: 400,
    sessionType: 'INDIVIDUAL',
    room: 'قاعة تنمية المهارات',
    notes: 'جلسة تركيز وانتباه والذاكرة البصرية',
    hasConflict: false,
    createdAt: '2026-02-15T08:30:00Z',
  },
  // Appointment 3: Today, Group session (1 Staff, 2 Children) - demonstrating 1:N
  {
    id: 'apt-3',
    childIds: ['child-3', 'child-4'],
    staffIds: ['staff-4'],
    date: today,
    startTime: '12:30',
    endTime: '13:30',
    status: 'SCHEDULED',
    sessionStatus: 'SCHEDULED',
    attendanceStatus: 'PENDING',
    paymentStatus: 'UNPAID',
    amount: 300,
    sessionType: 'GROUP',
    room: 'قاعة السلوك والتفاعل الاجتماعي',
    notes: 'جلسة جماعية لتنمية التفاعل الاجتماعي والتحدث أمام الآخرين',
    hasConflict: false,
    createdAt: '2026-02-16T09:00:00Z',
  },
  // Appointment 4: Today, Intentional overlapping conflict demonstration (same room or overlapping therapist time)
  {
    id: 'apt-4',
    childIds: ['child-5'],
    staffIds: ['staff-2'],
    date: today,
    startTime: '10:30', // Overlaps with apt-1 (10:00-10:45)
    endTime: '11:15',
    status: 'SCHEDULED',
    sessionStatus: 'SCHEDULED',
    attendanceStatus: 'PENDING',
    paymentStatus: 'UNPAID',
    amount: 350,
    sessionType: 'INDIVIDUAL',
    room: 'عيادة التخاطب 1',
    notes: 'موعد تداخل زمني تجريبي لاختبار إشعار التعارض المرئي',
    hasConflict: true, // Flagged visually, NOT blocked
    createdAt: '2026-02-17T10:00:00Z',
  },
  // Appointment 5: Tomorrow, Multi-therapist assessment (2 Staff, 1 Child) - demonstrating N:1
  {
    id: 'apt-5',
    childIds: ['child-4'],
    staffIds: ['staff-1', 'staff-3'],
    date: tomorrow,
    startTime: '14:00',
    endTime: '15:00',
    status: 'SCHEDULED',
    sessionStatus: 'SCHEDULED',
    attendanceStatus: 'PENDING',
    paymentStatus: 'UNPAID',
    amount: 500,
    sessionType: 'EVALUATION',
    room: 'قاعة التقييم الشامل',
    notes: 'تقييم مشترك بين د. خالد وأخصائي المهارات لتحديد الخطة الفردية',
    hasConflict: false,
    createdAt: '2026-02-18T11:00:00Z',
  },
  // Appointment 6: Completed yesterday
  {
    id: 'apt-6',
    childIds: ['child-1'],
    staffIds: ['staff-2'],
    date: yesterday,
    startTime: '10:00',
    endTime: '10:45',
    status: 'COMPLETED',
    sessionStatus: 'COMPLETED',
    attendanceStatus: 'PRESENT',
    paymentStatus: 'PAID',
    amount: 350,
    sessionType: 'INDIVIDUAL',
    room: 'عيادة التخاطب 1',
    notes: 'جلسة تخاطب أسبوعية منتهية',
    hasConflict: false,
    createdAt: '2026-02-10T12:00:00Z',
  },
];

export const initialAttendance: Attendance[] = [
  // Child attendance for yesterday's appointment
  {
    id: 'att-1',
    appointmentId: 'apt-6',
    participantId: 'child-1',
    participantType: 'CHILD',
    status: 'PRESENT',
    arrivalTime: '09:55',
    notes: 'حضر الطفل في الموعد برفقة والده',
    recordedAt: `${yesterday}T10:00:00Z`,
  },
  // Staff attendance for yesterday's appointment
  {
    id: 'att-2',
    appointmentId: 'apt-6',
    participantId: 'staff-2',
    participantType: 'STAFF',
    status: 'PRESENT',
    arrivalTime: '09:45',
    notes: 'الأخصائية متواجدة بالعيادة',
    recordedAt: `${yesterday}T09:50:00Z`,
  },
  // Child attendance for today's appointment (marked ready)
  {
    id: 'att-3',
    appointmentId: 'apt-1',
    participantId: 'child-1',
    participantType: 'CHILD',
    status: 'PRESENT',
    arrivalTime: '09:50',
    notes: 'في غرفة الانتظار',
    recordedAt: `${today}T09:50:00Z`,
  },
  // Staff attendance for today's appointment
  {
    id: 'att-4',
    appointmentId: 'apt-1',
    participantId: 'staff-2',
    participantType: 'STAFF',
    status: 'PRESENT',
    arrivalTime: '09:30',
    notes: '',
    recordedAt: `${today}T09:30:00Z`,
  },
];

export const initialPayments: Payment[] = [
  {
    id: 'pay-1',
    childId: 'child-1',
    parentId: 'parent-1',
    appointmentId: 'apt-6',
    amount: 350,
    paidAmount: 350,
    date: yesterday,
    paymentMethod: 'INSTAPAY',
    status: 'PAID',
    invoiceNumber: 'INV-2026-001',
    notes: 'سداد جلسة تخاطب فردية عبر إنستاباي',
    createdAt: `${yesterday}T10:45:00Z`,
  },
  {
    id: 'pay-2',
    childId: 'child-2',
    parentId: 'parent-2',
    appointmentId: 'apt-2',
    amount: 1200,
    paidAmount: 600,
    date: today,
    paymentMethod: 'CASH',
    status: 'PARTIAL',
    invoiceNumber: 'INV-2026-002',
    notes: 'دفعة مقدمة من باقة 4 جلسات تنمية مهارات (متبقي 600 ج.م)',
    createdAt: `${today}T09:15:00Z`,
  },
  {
    id: 'pay-3',
    childId: 'child-3',
    parentId: 'parent-3',
    amount: 300,
    paidAmount: 0,
    date: today,
    paymentMethod: 'CASH',
    status: 'UNPAID',
    invoiceNumber: 'INV-2026-003',
    notes: 'جلسة اليوم لم تسدد بعد',
    createdAt: `${today}T08:00:00Z`,
  },
];

export const initialSessions: Session[] = [
  {
    id: 'sess-1',
    childId: 'child-1',
    staffId: 'staff-2',
    appointmentId: 'apt-6',
    date: yesterday,
    durationMinutes: 45,
    sessionObjective: 'تثبيت نطق حرف الراء مع حركات الفتح والضم',
    notes: 'أبدى الطفل تجاوباً ممتازاً مع بطاقات الكلمات المصورة. تمكن من نطق (را - رو) بدون تردد، ويحتاج مزيد تدريب على (ري) في آخر الكلمة.',
    progressAssessment: 'EXCELLENT',
    homeRecommendations: 'تكرار التدريب المنزلي لمدة 10 دقائق يومياً باستخدام مرآة والكلمات المسجلة في كراسة المتابعة.',
    createdAt: `${yesterday}T11:00:00Z`,
  },
  {
    id: 'sess-2',
    childId: 'child-2',
    staffId: 'staff-3',
    date: '2026-02-12',
    durationMinutes: 45,
    sessionObjective: 'تدريبات تصنيف الأشكال والألوان وزيادة زمن الجلوس',
    notes: 'استمر الطفل في النشاط لمدة 18 دقيقة متواصلة بزيادة 5 دقائق عن الجلسة السابقة. تم العمل على ألعاب مطابقة المجسمات.',
    progressAssessment: 'GOOD',
    homeRecommendations: 'تقليل وقت الشاشات والأجهزة اللوحية واستبدالها بأنشطة الفك والتركيب.',
    createdAt: '2026-02-12T13:00:00Z',
  },
];

export const initialAppState: AppState = {
  currentRole: 'ADMINISTRATOR',
  currentUserId: 'staff-1',
  children: initialChildren,
  parents: initialParents,
  staff: initialStaff,
  appointments: initialAppointments,
  attendance: initialAttendance,
  payments: initialPayments,
  sessions: initialSessions,
  isLoading: false,
};
